### ISSUE TITLE
skip CheckLegalese via environment variable

### ISSUE THREAD

**Issue by kumavis** [ethereum/go-ethereum#1992]
Feature Request: Allow legalese to be skipped by correct value in environment variable.

up-side: more semantic means of skipping the legalese. ~~also official docker image works as-is.~~
down-side: ?

I understand that you can achieve this by creating the data directory first~~, but unfortunately there doesn't seem to be a way to do this with `docker-compose` when using the official image ( need to create a silly wrapper image ).~~

sorry for overly specific use-case concerns. :smile_cat:

**Comment by kumavis** [comment]
if you set the volumes like this in `docker-compose.yml` it will work:
```yml
ethNode:
  image: ethereum/client-go
  volumes:
    - /var/data/geth:/root/.ethereum
```
