### ISSUE TITLE
Null pointer exception in light mode

### ISSUE THREAD

**Issue by eiabea** [ethereum/go-ethereum#21511]
#### System information

Geth version: `geth version`: v1.9.20-stable-979fc968
OS & Version: Windows/Linux/OSX: Debian 4.19.0-10-amd64 / Docker 18.09.1
Commit hash : (if `develop`)

#### Expected behaviour

Node runs without null pointers

#### Actual behaviour

Node crashes due to a null pointer exception

#### Steps to reproduce the behaviour

1. Start docker container with following `docker-compose.yml`
```
version: "3"

services:
  geth:
    image: ethereum/client-go:v1.9.20
    restart: unless-stopped
    command: "--syncmode light --http --http.addr 0.0.0.0"
    volumes:
      - "./data:/root"
```
2. Wait about 3 hours until error occurs

#### Backtrace

````
geth_1  | INFO [09-02|11:45:51.541] Imported new block headers               count=192  elapsed=259.163ms number=10779558 hash="1c0744…7e0293" age=7h41m13s
geth_1  | panic: runtime error: invalid memory address or nil pointer dereference
geth_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xd25a18]
geth_1  | 
geth_1  | goroutine 93 [running]:
geth_1  | github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc0003cb4a0, 0x149f340, 0xc00288cc60, 0xc0014c7440, 0xc00288cc60, 0xc0015accc0, 0x46b52c)
geth_1  | 	github.com/ethereum/go-ethereum/light/txpool.go:229 +0x238
geth_1  | github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc0003cb4a0, 0xc0014c7440)
geth_1  | 	github.com/ethereum/go-ethereum/light/txpool.go:310 +0xf7
geth_1  | github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc0003cb4a0)
geth_1  | 	github.com/ethereum/go-ethereum/light/txpool.go:291 +0x56
geth_1  | created by github.com/ethereum/go-ethereum/light.NewTxPool
geth_1  | 	github.com/ethereum/go-ethereum/light/txpool.go:108 +0x3da
````
