### ISSUE TITLE
502 error when behind Apache reverse proxy

### ISSUE THREAD

**Issue by promethe42** [ethereum/go-ethereum#2157]
Hello,

first of all thank you for the great work!

I'm trying to use the JSON-RPC API behind an Apache Reverse Proxy.
Here is the corresponding configuration:

```
ProxyPass           /blockchain/ http://localhost:8545/
ProxyPassReverse    /blockchain/ http://localhost:8545/
```

The web browser can connect to `/blockchain/` "most of the time" (3 out of 5 times I would say).
But sometimes, I get a 502 (Bad Gateway) error.

Here is what I get in the Apache error logs:

```
[Fri Jan 29 00:05:40.376821 2016] [proxy:error] [pid 1184:tid 140209534494464] (32)Broken pipe: [client 192.168.50.1:58045] AH01084: pass request body failed to 127.0.0.1:8545 (127.0.0.1), referer: http://cocorico.cc.test/blockchain-test/
[Fri Jan 29 00:05:40.376843 2016] [proxy_http:error] [pid 1184:tid 140209534494464] [client 192.168.50.1:58045] AH01097: pass request body failed to 127.0.0.1:8545 (127.0.0.1) from 192.168.50.1 (), referer: http://cocorico.cc.test/blockchain-test/
```

I don't have this issue when I use testrpc instead of geth.

How can I solve this?

Thank you,

**Comment by promethe42** [comment]
It looks like adding `ProxyTimeout 300` to the Apache configuration solves the issue.

**Comment by promethe42** [comment]
After further testing setting `ProxyTimeout 300` is not the solution and I still get 502 errors.

**Comment by karalabe** [comment]
Is this happening with the stable branch or latest develop?

**Comment by promethe42** [comment]
I'm using the ppa. Here is my Ansible setup:

```
- name: add ethereum PPAs
  apt_repository: repo={{ item }}
  with_items:
    - ppa:ethereum/ethereum
    - ppa:ethereum/ethereum-dev
    - ppa:ethereum/ethereum-qt

- name: install ethereum
  apt: name={{ item }} update_cache=yes
  with_items:
    - ethereum
    - cpp-ethereum
```
