### ISSUE TITLE
err="authentication needed: password or unlock"

### ISSUE THREAD

**Issue by hysci** [ethereum/go-ethereum#21915]
#### System information

Geth version: `geth version`

Geth
Version: 1.9.25-unstable
Git Commit: fa572cd2971fda0bf773d2817acb23385bac66c7
Git Commit Date: 20201127
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=go

OS & Version: Windows/Linux/OSX

Ubuntu 20.04

Commit hash : (if `develop`)

docker-compose.yml

```
version: "3"
services:
    web:
        image: ethereum/client-go
        container_name: client-go
        ports:
            - 30303:30303
            - 8545:8545
            - 8546:8546
        restart: always
        volumes:
            - local:/root
        command: --unlock a047032e0239a2fc04f2124923f8a51eebb8123a --password /root/.ethereum/passwd --allow-insecure-unlock --networkid 1 --syncmode "full"  --maxpeers 1024 --maxpendpeers 900  --http --http.addr 0.0.0.0 --http.corsdomain="*" --http.vhosts="*" --http.api "admin,eth,miner,net,personal,shh,txpool,web3" --ws --ws.addr 0.0.0.0 --ws.origins="*" --ws.api "admin,eth,miner,net,personal,shh,txpool,web3"
volumes:
    local: {}
```

docker-compose up -d

#### Expected behaviour

Nothing wrong

#### Actual behaviour

> account is successfully unlocked because --unlock and --password are assigned
> geth attach, then personal.listAccount, the account[0] listed is exactly what --unlock is set
> the error still happens
WARN [11-28|14:16:02.262] Served eth_signTransaction               conn=10.30.44.5:50154 reqid=231 t="11.689µs"   err="authentication needed: password or unlock"

#### Steps to reproduce the behaviour

> Copy the above docker-compose.yml into a folder
> Copy keystore into /var/lib/docker/volumes/core-geth_local/_data/.ethereum/keystore/
> Copy password file into /var/lib/docker/volumes/core-geth_local/_data/.ethereum/passwd
> docker-compose up -d
> docker ps (get image hash)
> docker logs hash# -f (observe error/warn message)

#### Backtrace

````
[backtrace]
````
