### ISSUE TITLE
Several crashes with ethereum/client-go:v1.9.24 container

### ISSUE THREAD

**Issue by nicolinux** [ethereum/go-ethereum#21939]
This is a fresh install running on an Intel NUC 10th generation. Here is the relevant part of my docker-compose:

```
  geth:
    image: ethereum/client-go:v1.9.24
    restart: always
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
    volumes:
      - ./data/geth:/root/.ethereum
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --nousb --http --http.addr=0.0.0.0 --http.port=8545 --http.vhosts="*" --http.corsdomain="*" --http.api="eth,net"
```

#### System information

Geth version: `1.9.24`
OS & Version: Ubuntu 20.x

#### Expected behaviour
Perform full sync on mainnet

#### Actual behaviour
Crashes with:
1.
```
fatal error: unexpected signal during runtime execution

[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x423050]
```

or

2.
```
unexpected fault address 0x0

fatal error: fault

[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xc9c502]
```

or

3. 
```
panic: leveldb: internal key xxx corrupted: invalid type
```

#### Steps to reproduce the behaviour
Just start a full sync.

#### Backtrace

Attached the (big) log of that container. Several geth restarts and crashes. I understand that the db got corrupted, but the question is why and how to avoid it :)

[geth-docker-crashlogs.txt](https://github.com/ethereum/go-ethereum/files/5625495/geth-docker-crashlogs.txt)
