### ISSUE TITLE
Listen to new blocks/txs/receipts being added

### ISSUE THREAD

**Issue by kosciolek** [ethereum/go-ethereum#24100]
I'd like to push the chain into an external database, preferably as soon as new data comes to the node, and preferably with the fast/snap algorithm.

Currently, I've written a crude mechanism to achieve so, by injecting some code around this https://github.com/ethereum/go-ethereum/blob/72c2c0ae7e2332b08d3e1ebfe5f850a92e26e8a1/core/blockchain.go#L1595 since this the only point I found where I've got easy access to all blocks, transactions and receipts at once.

The problems with that are:
* I suspect sooner or later the db will not be in sync the node, since the node might modify the chain later for some reasons (I'm not well acquainted with Ethereum, but I think transactions can be rollbacked?)
* That part of code is executed only with the full sync algorithm, which is way too slow.

Please point me in the right direction. Which parts of code should I look at?

Judging by console messages, the snap algorithm
* first goes through InsertHeaderChain
https://github.com/ethereum/go-ethereum/blob/72c2c0ae7e2332b08d3e1ebfe5f850a92e26e8a1/core/headerchain.go#L375 which inserts only block headers.
* then it goes through InsertReceiptChain https://github.com/ethereum/go-ethereum/blob/72c2c0ae7e2332b08d3e1ebfe5f850a92e26e8a1/core/blockchain.go#L874 to complete the previously inserted headers with transaction and receipt data.

* Could hooking into these functions solve my problem?
* What mechanisms could potentially cause the database to become desynchronized?

PS. Is is possible to hot reload during development? Currently I recompile the entire project after every change.

**Comment by kosciolek** [comment]
Sorry, looks like it added the docs label automatically. I didn't mean this :/

**Comment by s1na** [comment]
In your place I wouldn't modify the code to get this data. You need to handle various cases (like re-orgs as you yourself mentioned). Re re-orgs: theoretically geth considers blocks that are 90,000 levels deep as "un-reorgable". But most common re-orgs are <10 levels deep.

Anyway so to get the chain data you can just use the JSON-RPC [API](https://eth.wiki/json-rpc/API) of a live node. E.g. use `eth_getBlockByNumber(<num>, true)` to get the block and its transactions, and then `eth_getTransactionReceipt(<txHash>)` to get the receipt for each of those transactions.

Unless that somehow doesn't meet your requirements?

> PS. Is is possible to hot reload during development? Currently I recompile the entire project after every change.

No that's not possible.

**Comment by kosciolek** [comment]
@s1na I tried the JSON-RPC API already.

My geth config was as follows:
```
  geth:
    build: ./geth
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - chaindata:/chaindata
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      # Don't sync if less than ~10gb of free space
      - --datadir.minfreedisk=10000
      # Index all transactions
      - --txlookuplimit=0
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --datadir
      - "/chaindata"
      # Megabytes of memory allocated to internal caching (default: 1024)
      - --cache=4096
      # Maximum number of network peers (network disabled if set to 0) (default: 25)
      # - --maxpeers=100
      - --lightkdf
      # Blockchain sync mode ("fast", "full", or "light")
      - --syncmode=fast
      # Blockchain garbage collection mode ("full", "archive") (default: "full")
      - --gcmode=archive
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```

Unfortunately it's proven way too slow, somehow.

The system worked like this:
* Geth's syncing via snap
* Another program is fetching all blocks, from 0 to the last blocks, doing a few requests in parallel
* The program starts falling behind geth, and the gap increases
* After fetching 2-3 mill blocks (sometimes lower, sometimes higher), geth starts choking and even a single request takes a lot of time. It makes me think that it's expensive for geth to return old blocks, i.e. if it's already syncing block 8mill, but you request block 4mill, it takes a lot of time to dig it out. I had `txlookuplimit=0` and `gcmode=archive` though
