### ISSUE TITLE
Clean sync Goerli broken(?) post merge on 1.10.21 and 1.10.23

### ISSUE THREAD

**Issue by ulope** [ethereum/go-ethereum#25693]
#### System information

Geth version: `v1.10.21` / `v1.10.23`
OS & Version: Linux

#### Expected behaviour

A fresh sync from scratch of Goerli to work

#### Actual behaviour

Does not work.
- Geth `1.10.21`: 
  - Snap sync completes, afterwards State heal seems to continue indefinitely (aborted after 4 days)
  - Last state heal log before abort:
    `INFO [09-05|14:37:35.138] State heal in progress                   accounts=9@647.00B            slots=0@0.00B              codes=0@0.00B            nodes=16,319,436@8.09GiB   pending=4369`
  - Many, many `Unexpected trienode heal packet` messages (~70% of all log lines)
  - Pivot is only changed 12 times. Last one:
    `WARN [09-02|16:42:58.589] Pivot seemingly stale, moving            old=7,516,913 new=7,516,977`
  - Suspiciously new blocks are no longer imported: 
    `INFO [09-05|14:37:34.872] Imported new block headers               count=0    elapsed=15.422ms    number=7,382,818 hash=aa32c4..48c7cc age=3w4d12h    ignored=178` 
    - Probably because of:
      `Local chain is post-merge, waiting for beacon client sync switch-over...`
    - However Prsym claims geth is not synced:
      `level=error msg="Unable to process past deposit contract logs, perhaps your execution client is not fully synced" error="no contract code at given address" prefix=powchain`
- Geth `1.10.23`:
  - Syncing never even starts
    No sync progress is reported, apparently every peer is dropped because of:
    `WARN [09-06|09:25:04.945] Snapshot extension registration failed   peer=6de3885d err="peer connected on snap without compatible eth support"`

#### Steps to reproduce the behaviour

Compose file used:
```yaml
version: "3"

services:
  geth:
    image: ethereum/client-go:v1.10.23
    restart: always
    network_mode: host
    stop_grace_period: 1m
    volumes:
      - /data/geth:/data
      - jwt:/jwt
    command: >
      --goerli
      --datadir=/data
      --http
      --http.api eth,net,web3,txpool
      --http.addr 0.0.0.0
      --http.corsdomain '*'
      --ws
      --ws.api eth,web3,net
      --authrpc.jwtsecret /jwt/jwtsecret
      --authrpc.vhosts '*'
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=9191

  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: always
    network_mode: host
    volumes:
      - /data/prysm:/data
      - jwt:/jwt
    command: >
      --goerli
      --datadir=/data
      --rpc-host=0.0.0.0
      --http-web3provider=http://localhost:8551
      --jwt-secret=/jwt/jwtsecret
      --accept-terms-of-use

volumes:
  jwt:
```
