### ISSUE TITLE
Blocks are always behind

### ISSUE THREAD

**Issue by messagebox-link** [ethereum/go-ethereum#25915]
Since the merger, the block has not been able to catch up with the latest block, and has always been behind by about 100 blocks. How should the configuration be used to catch up.
Node runs on docker
docker-compose.yaml file :
``` yaml
version: "3"
services:
    beacon_node:
        image: sigp/lighthouse:v3.1.2
        volumes:
          - /data/ligthouse:/root
        ports:
          - 127.0.0.1:5052:5052/tcp
          - 9000:9000/tcp
          - 9000:9000/udp
        entrypoint: ["lighthouse", "--network", "mainnet", "--datadir", "/root/", "beacon_node", "--http", "--http-address", "0.0.0.0", "--execution-endpoint", "http://geth:8551", "--execution-jwt", "/root/jwtsecret"]
        restart: on-failure
        stop_grace_period: 3m
    geth:
        image: ethereum/client-go:v1.10.25
        volumes:
         - /data/geth-data:/root
        ports:
          - 30303:30303/tcp
          - 30303:30303/udp
          - 46834:46834/udp
          - 8546:8546/tcp
        expose:
            - 8551
        entrypoint: ["geth", "--ipcdisable", "--syncmode", "snap", "--mainnet", "--datadir", "/root", "--http",  "--http.addr", "0.0.0.0", "--http.vhosts", "*", "--authrpc.addr","0.0.0.0", "--authrpc.vhosts": "*", "--authrpc.jwtsecret", "/root/jwtsecret", "--http.api", "eth,net", "--ws", "--ws.addr", "0.0.0.0", "--ws.vhosts", "*"]
        restart: on-failure
        stop_grace_period: 3m
```

#### Some check cases:

1. By checking the consensus node synchronization status

``` shell
    Request: curl http://127.0.0.1:5052/lighthouse/syncing  
    Result: {"data":"Synced"}
```
2. Obtaining finalized checkpoint & state root

``` shell
    Request: curl http://127.0.0.1:5052/eth/v1/beacon/headers/finalized 
    Result:  {"execution_optimistic":true,"data":{"root":"0x5b14dff435f7d1775c51e979d21f1f32d6a0a34621ae59ea28e9951f56cc05bc","canonical":true,"header":{"message":{"slot":"4822464","proposer_index":"178599","parent_root":"0xbafb6eb299e6853450d53f571a729d17915a1513eb551ad7ff2cba86c917eea8","state_root":"0xd43efd1917a711ac5e5ea419ad44b41d96ffcc1f637c775cbbcf3bafebb807ec","body_root":"0x73897dc8a0626973122df73e5ace05a6b9dcb5d6c373042222e46f22e785a5cc"},"signature":"0xa270f4461965fd571b02f0b9f80808ad9aa063ec961660b200225ffd770212a8a8dbb3e1f6c59286a56c4040f3144ed61326264248976421c47dafc94a4c3a7ba62161cc2882506c73845b732e327fcc24ec808f976dd28bea4fa9ff4f7b99d2"}}}
```
3. Check execution node sync status

```shell
    Request: curl -X POST --data '{"jsonrpc": "2.0", "method":"eth_syncing", "params":[],"id": 1}' http://127.0.0.1:8545 -H "Content-Type: application/json"   
    Result:  {"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0xeeef19","healedBytecodeBytes":"0x2b2875f9","healedBytecodes":"0x16d16","healedTrienodeBytes":"0x29d7eedfc1","healedTrienodes":"0x23e1c6f3","healingBytecode":"0x0","healingTrienodes":"0x461","highestBlock":"0xeeef83","startingBlock":"0xeed623","syncedAccountBytes":"0x9b2c4360a","syncedAccounts":"0xa5e0b6a","syncedBytecodeBytes":"0xc418a4c4","syncedBytecodes":"0x81bae","syncedStorage":"0x26e0bebc","syncedStorageBytes":"0x208521c47f"}}
```

4. getSyncingStatus  

```shell
    Request: curl http://127.0.0.1:5052/lighthouse/eth1/syncing 
    Result: {"data":{"head_block_number":null,"head_block_timestamp":null,"latest_cached_block_number":null,"latest_cached_block_timestamp":null,"voting_target_timestamp":1664647255,"eth1_node_sync_status_percentage":0.0,"lighthouse_is_cached_and_ready":false}}
```

#### Some log information:
1. beacon_node
``` log
beacon_node_1  | Oct 02 07:29:52.247 WARN Execution endpoint is not synced        action: trying fallback, last_seen_block_unix_timestamp: 0, endpoint: http://geth:8551/, auth=true, service: deposit_contract_rpc                                                                             
beacon_node_1  | Oct 02 07:29:52.247 ERRO No synced execution endpoint            advice: ensure you have an execution node configured via --execution-endpoint or if pre-merge, --eth1-endpoints, service: deposit_contract_rpc                                                                
beacon_node_1  | Oct 02 07:29:52.247 ERRO Error updating deposit contract cache   error: "All fallbacks errored: http://geth:8551/, auth=true => EndpointError(FarBehind)", retry_millis: 60000, service: deposit_contract_rpc                                                                  
beacon_node_1  | Oct 02 07:29:53.001 WARN Head is optimistic                      execution_block_hash: 0x5d945e42ed84a6dd76c9461668e41a477384f2e967a9f9e19758266d75f469e1, info: chain not fully verified, block and attestation production disabled until execution engine syncs, service: slot_notifier                                                                                                                                      
beacon_node_1  | Oct 02 07:29:53.001 INFO Synced                                  slot: 4822647, block: 0xf17d…eea9, epoch: 150707, finalized_epoch: 150705, finalized_root: 0x28c6…8b0e, exec_hash: 0x5d94…69e1 (unverified), peers: 14, service: slot_notifier                                
beacon_node_1  | Oct 02 07:29:53.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier                                                                                    

```
