### ISSUE TITLE
ethdb: storage pebble uses 100% cpu to compaction

### ISSUE THREAD

**Issue by jsvisa** [ethereum/go-ethereum#26712]
#### System information

Geth version: `geth version`
CL client & version: e.g. lighthouse/nimbus/prysm@v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

I'm running go-ethereum v1.11.0 in docker with snap-syncing(resync from genesis). 

<details><summary>docker-compose as below 👇</summary>
<p>

```yaml
version: '3'

services:
  geth-full:
    image: ethereum/client-go:v1.11.0
    container_name: geth-full
    command:
      - '--db.engine=pebble'
      - '--syncmode=snap'
      - '--datadir=/data'
      - '--cache.preimages'
      - '--cache=4120'
      - '--cache.database=60'
      - '--cache.trie=30'
      - '--cache.gc=5'
      - '--cache.snapshot=5'
      - '--cache.trie.rejournal=48h'
      - '--maxpeers=200'
      - '--port=40303'
      - '--http'
      - '--http.addr=0.0.0.0'
      - '--http.port=4545'
      - '--http.api=engine,web3,eth,net,personal,miner,txpool,debug,admin'
      - '--ws'
      - '--ws.addr=0.0.0.0'
      - '--ws.port=4546'
      - '--ws.origins=*'
      - '--ws.api=engine,web3,eth,net,personal,miner,txpool,debug,admin'
      - '--authrpc.addr=0.0.0.0'
      - '--authrpc.port=8551'
      - '--authrpc.vhosts=*'
      - '--authrpc.jwtsecret=/jwt/jwt.hex'
      - '--http.vhosts=*'
      - '--http.corsdomain=*'
      - '--metrics'
      - '--metrics.addr=0.0.0.0'
      - '--metrics.port=6040'
      - '--pprof'
      - '--pprof.addr=0.0.0.0'
      - '--pprof.port=6041'
    volumes:
      - /md0/geth-fast/data:/data
      - /md0/geth-fast/jwt:/jwt
    restart: unless-stopped
    network_mode: host

  prysm:
    image: prysmaticlabs/prysm-beacon-chain:v3.2.0
    container_name: eth-prysm
    command:
      - '--mainnet'
      - '--datadir=/data'
      - '--http-web3provider=http://127.0.0.1:4545'
      - '--rpc-host=0.0.0.0'
      - '--rpc-port=9547'
      - '--monitoring-host=0.0.0.0'
      - '--execution-endpoint=http://127.0.0.1:8551'
      - '--jwt-secret=/jwt/jwt.hex'
      - '--accept-terms-of-use'
      - '--grpc-gateway-host=0.0.0.0'
      - '--grpc-gateway-corsdomain=*'
      - '--checkpoint-sync-url=https://beaconstate.info/'
      - '--genesis-beacon-api-url=https://beaconstate.info/'
    volumes:
      - /md0/geth-fast/prysm:/data
      - /md0/geth-fast/jwt:/jwt
    network_mode: host
    restart: unless-stopped
```

</p>
</details>

This caused my node using 100% CPU in the pebble compacting(see the profile file for more detail)

<img width="528" alt="image" src="https://user-images.githubusercontent.com/3627395/219393112-f7212d5a-5b6e-44fc-a2ac-e01706afc789.png">

[pprof.geth.samples.cpu.003.pb.gz](https://github.com/ethereum/go-ethereum/files/10756962/pprof.geth.samples.cpu.003.pb.gz)

Seems we are using all the CPU for compaction here https://github.com/ethereum/go-ethereum/blob/13d7de77f40b2c2bdcece96a06f6b7f89c0026cf/ethdb/pebble/pebble.go#L167

Yes, I can set `--cpu=2` to limit the CPU quota in docker container, but it can't take an effort on pebble's side, so IMHO

1. use https://github.com/uber-go/automaxprocs to set the correct CPU quota?
2. set with command line argument?

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.
