### ISSUE TITLE
Beacon client online, but no consensus updates received in a while even though lighthouse is synced

### ISSUE THREAD

**Issue by GopherJ** [ethereum/go-ethereum#26784]
#### System information

Geth version: `ethpandaops/geth:master`
CL client & version: e.g. sigp/lighthouse:capella
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

Geth should start to sync if lighthouse finished syncing

#### Actual behaviour

Geth is not starting

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/222068213-959f49b2-bbfc-4953-89d0-d316dbfa0790.png)

**Comment by GopherJ** [comment]
You should be able to reproduce by:

1. install ethdo
```
go install github.com/wealdtech/ethdo@latest
```
2. clone paraspace-core then switch to feat/validator-launch
```
git clone https://github.com/para-space/paraspace-core
cd paraspace-core
git checkout feat/validator-launch
```
3. touch .env
```
NETWORK=zhejiang
ETHERSCAN_VERIFICATION=false
ETHERSCAN_VERIFICATION_CONTRACTS=
MOCHA_JOBS=1
DB_PATH=deployed-contracts.json
```
4. install deps
```
make init
```
6. generate docker-compose which has lighthouse-validator,geth,lighthouse-consensus
```
make setup-validators
```
7. launch
```
cd app
docker-compose up -d --build
```
8. wait and check `-execution` logs

**Comment by GopherJ** [comment]
example of generated docker-compose

```
version: "3.7"
services:
  validator1-consensus:
    ports:
      - 5052:5052
    volumes:
      - validator1-data:/data
    build:
      context: .
      dockerfile: consensusLayer.Dockerfile
    command:
      - lighthouse
      - --testnet-dir=/app
      - bn
      - --eth1
      - --http
      - --http-allow-sync-stalled
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --discovery-port=9000
      - --boot-nodes=enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk,enr:-Ly4QOS00hvPDddEcCpwA1cMykWNdJUK50AjbRgbLZ9FLPyBa78i0NwsQZLSV67elpJU71L1Pt9yqVmE1C6XeSI-LV8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhEDhTgGJc2VjcDI1NmsxoQIgMUMFvJGlr8dI1TEQy-K78u2TJE2rWvah9nGqLQCEGohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA,enr:-MK4QMlRAwM7E8YBo6fqP7M2IWrjFHP35uC4pWIttUioZWOiaTl5zgZF2OwSxswTQwpiVCnj4n56bhy4NJVHSe682VWGAYYDHkp4h2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhJK-7tSJc2VjcDI1NmsxoQLDq7LlsXIXAoJXPt7rqf6CES1Q40xPw2yW0RQ-Ly5S1YhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA,enr:-MS4QCgiQisRxtzXKlBqq_LN1CRUSGIpDKO4e2hLQsffp0BrC3A7-8F6kxHYtATnzcrsVOr8gnwmBnHYTFvE9UmT-0EHh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhKXoVKCJc2VjcDI1NmsxoQK6J-uvOXMf44iIlilx1uPWGRrrTntjLEFR2u-lHcHofIhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-LK4QOQd-elgl_-dcSoUyHDbxBFNgQ687lzcKJiSBtpCyPQ0DinWSd2PKdJ4FHMkVLWD-oOquXPKSMtyoKpI0-Wo_38Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDuKNezAAAAckYFAAAAAAAAgmlkgnY0gmlwhES3DaqJc2VjcDI1NmsxoQNIf37JZx-Lc8pnfDwURcHUqLbIEZ1RoxjZuBRtEODseYN0Y3CCIyiDdWRwgiMo,enr:-KG4QLNORYXUK76RPDI4rIVAqX__zSkc5AqMcwAketVzN9YNE8FHSu1im3qJTIeuwqI5JN5SPVsiX7L9nWXgWLRUf6sDhGV0aDKQ7ijXswAAAHJGBQAAAAAAAIJpZIJ2NIJpcIShI5NiiXNlY3AyNTZrMaECpA_KefrVAueFWiLLDZKQPPVOxMuxGogPrI474FaS-x2DdGNwgiMog3VkcIIjKA
      - --suggested-fee-recipient=0x018281853eCC543Aa251732e8FDaa7323247eBeB
      - --datadir=/data/lighthouse
      - --jwt-secrets=/app/jwtsecret
      - --execution-endpoints=http://validator1-execution:8551
      - --http-address=0.0.0.0
      - --http-port=5052
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  validator1-execution:
    ports:
      - 8551:8551
      - 8545:8545
    volumes:
      - validator1-data:/data
    build:
      context: .
      dockerfile: executionLayer.Dockerfile
    command:
      - --http
      - --http.api=engine,eth,web3,net,debug
      - --ws
      - --ws.api=engine,eth,web3,net,debug
      - --http.corsdomain=*
      - --syncmode=full
      - --bootnodes=enode://691c66d0ce351633b2ef8b4e4ef7db9966915ca0937415bd2b408df22923f274873b4d4438929e029a13a680140223dcf701cabe22df7d8870044321022dfefa@64.225.78.1:30303,enode://89347b9461727ee1849256d78e84d5c86cc3b4c6c5347650093982b726d71f3d08027e280b399b7b6604ceeda863283dcfe1a01e93728b4883114e9f8c7cc8ef@146.190.238.212:30303,enode://c2892072efe247f21ed7ebea6637ade38512a0ae7c5cffa1bf0786d5e3be1e7f40ff71252a21b36aa9de54e49edbcfc6962a98032adadfa29c8524262e484ad3@165.232.84.160:30303,enode://71e862580d3177a99e9837bd9e9c13c83bde63d3dba1d5cea18e89eb2a17786bbd47a8e7ae690e4d29763b55c205af13965efcaf6105d58e118a5a8ed2b0f6d0@68.183.13.170:30303,enode://2f6cf7f774e4507e7c1b70815f9c0ccd6515ee1170c991ce3137002c6ba9c671af38920f5b8ab8a215b62b3b50388030548f1d826cb6c2b30c0f59472804a045@161.35.147.98:30303
      - --datadir=/data/geth
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/app/jwtsecret
      - --networkid=1337803
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  validator1-validator:
    ports: []
    volumes:
      - validator1-data:/data
    build:
      context: .
      dockerfile: validator.Dockerfile
    command:
      - lighthouse
      - --testnet-dir=/app
      - vc
      - --suggested-fee-recipient=0x018281853eCC543Aa251732e8FDaa7323247eBeB
      - --datadir=/data/lighthouse/validator-data
      - --beacon-nodes=http://validator1-consensus:5052
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
volumes:
  validator1-data:
    external: true

```
