### ISSUE TITLE
Geth not starting sync with Docker

### ISSUE THREAD

**Issue by dbdevc** [ethereum/go-ethereum#26810]
#### System information

Geth
Version: 1.11.3-unstable
Git Commit: 27e59827d804b0112c4213465ff3b902e25cb6d9
Architecture: arm64
Go Version: go1.20.1
Operating System: linux
GOPATH=
GOROOT=

Im running a GETH node with Docker on a Raspberry Pi4 and it's doing a fresh sync (no previous db, etc., just a new jwt for beacon client) on snap mode. I have port forwarding correctly enabled, and the beacon client (nimbus) had no problem syncing until the merge slots, after which it stopped as GETH isn't synced. This is a part of my docker-compose file that is relevant to the GETH node:

```yaml
version: "3.8"

services:
  geth:
    image: ethereum/client-go:latest
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - <SSD>/ethereum:/root/.ethereum/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 127.0.0.1:8545:8545
      - 127.0.0.1:8546:8546
      - 127.0.0.1:8551:8551
    command:
      - --cache=2048
      - --http
      - --http.api=txpool,eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --maxpeers=64
      - --ws.api=txpool,eth,net,web3,engine,admin
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
      - --nat=extip:<my static ip>
    <<: *logging  
  ```
  
 `eth.syncing` always returns false. The node has been online for nearly 20 days, and I don't have issues with finding and connecting to peers. I expect GETH to start syncing or provide any relevant error messages as to why it hasn't. Even with debug level 5, the only information I got was related to incoming and outgoing connections. There have not been any downtimes or unexpected shutdowns.

You can find an excerpt from the logs [here](https://gist.github.com/dbdevc/b83ea11f7aa9611e82eb63152536c5f5). I restarted the node recently and only provided the initial startup logs below, but the only things are these warning messages and nothing else. Right now I'm on the unstable version but this issue persists on `Geth/v1.11.2-stable-73b01f40/linux-arm64/go1.20.1` as well.

I should also note that I was able to sync completely around 2022 August without using Docker on the same Raspberry Pi.
