### ISSUE TITLE
geth node starts syncing from the beginning

### ISSUE THREAD

**Issue by philipp1992** [ethereum/go-ethereum#26811]
Hi,
i run geth for goerli like this:

```
          image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
          args:
            - '--datadir=/data'
            - '--jwt-secret=/jwt/jwt.hex'
            - '--rpc-host=0.0.0.0'
            - '--grpc-gateway-host=0.0.0.0'
            - '--monitoring-host=0.0.0.0'
            - '--execution-endpoint=http://localhost:8551'
            - >-
              --checkpoint-sync-url=https://goerli.checkpoint-sync.ethpandaops.io
            - >-
              --genesis-beacon-api-url=https://goerli.checkpoint-sync.ethpandaops.io
            - '--prater'
            - '--accept-terms-of-use'
```
```
 image: ethereum/client-go:v1.10.25
          command:
            - geth
          args:
            - '--http'
            - '--authrpc.jwtsecret'
            - /root/.ethereum/jwt.hex
            - '--authrpc.addr'
            - 0.0.0.0
            - '--authrpc.vhosts=*'
            - '--http.addr'
            - 0.0.0.0
            - '--ws'
            - '--ws.addr'
            - 0.0.0.0
            - '--ws.origins=*'
            - '--goerli'
            - '--http.vhosts=*'
            - '--http.api=admin,debug,eth,miner,net,personal,shh,txpool,web3'
            - '--syncmode'
            - full
            - '--verbosity=4'
            - '--v5disc'
            - '--nat=extip:xx'
            - '--snapshot=false'
            - >-
              --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@xxxx

```

i have started the containers about 90 days ago. Now my hoster had a problem, the VM had no internet for 4 hours and i had to restart the server with the geth container.

Checked the Geth logs and realized, that it is about 90 days behind and syncing again from there.
I have persistet the ~/.ethereum directory and can confirm there are 200GB of files there, so its not a loss of data per se.

What could be the reason that my geth node has to sync from 90 days instead of just from the outage onwards?
kind regards
Philipp
