### ISSUE TITLE
Enable GitHub Advanced Security - Code Scanning for this repository

### ISSUE THREAD

**Issue by ghsioux** [ethereum/go-ethereum#27351]
# Rationale

Hello team,

First, a big thank you for this great work, you rock. I was wondering whether you'd like to appreciate [GitHub CodeQL code scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning) for this repository. This is free for public repository and can be useful to detect vulnerabilities in the code. 

As an example, I have forked the repo, enabled code scanning and found about 12 medium-to-high vulnerability in the whole C/Javascript/Go codebase. Of course, these vulnerabilities should be reviewed by security specialist to ensure they are not false-positive, but we never know!

I can share more details about these findings in private if needed.

I'm working at GitHub so I would be happy to help you if you're interested, it's pretty quick to setup and it would improve the overall security level of geth. 

# Implementation

Code scanning must be enabled by a repo admin in the repo settings.

Then, a GitHub Actions workflow file must be created for CodeQL, e.g. one like that:

```
name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '43 7 * * 5'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'c', 'go', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        # queries: security-extended,security-and-quality

    # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
```

We could further secure the development lifecycle by setting this workflow as a required check in the branch protection rules of your main branch.
