### ISSUE TITLE
Error when restarting devnet POS

### ISSUE THREAD

**Issue by neodiz** [ethereum/go-ethereum#28073]
I'm trying to start POS. I do everything by [url](https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet) . The network is up and running. After a restart, the network stops working. The error is below. Addressed this problem to the prysm community [result](https://github.com/OffchainLabs/eth-pos-devnet/issues/19#issuecomment-1705565066). Can you help please?

#### System information
Geth version: `Geth/v1.12.2-stable-bed84606/linux-amd64/go1.20.7`
CL client & version: prysm 4.7
OS & Version: Linux 
#### Geth params docker 
````
  geth1:
    image: "ethereum/client-go:stable"
    command:
      - --http
      - --http.api=eth,web3,txpool,net
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/jwtsecret
      - --datadir=/data
      - --allow-insecure-unlock
      - --unlock=<wallet>
      - --password=/data/geth_password.txt
      - --syncmode=full
      - --networkid=${CHAIN_ID:-32383}
    volumes:
      - ./root_signer:/data
      - ./jwtsecret:/jwtsecret
````

#### Backtrace

````
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=4 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=64
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=8 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=128
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=12 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=192
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=16 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=256
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=20 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=320
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=24 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=384
time="2023-09-07 09:46:41" level=debug msg="Can not trigger event" epoch=28 error="slot is higher than the finalized slot" event=tick highestExpectedSlot=16 noRequiredPeersErrRetries=0 prefix=initial-sync start=448
````
