### ISSUE TITLE
Metrics options are ignored in config.toml

### ISSUE THREAD

**Issue by VladStarr** [ethereum/go-ethereum#28303]
#### System information

Geth version: 1.13.2-stable
CL client & version: prysm v4.0.8
OS & Version: Linux
Commit hash :

#### Expected behaviour

Options specified in config should enable metrics collection.

```toml
[Metrics]
Enabled = true
EnabledExpensive = true
```

#### Actual behaviour

These options are ignored. Metrics server starts on 6060 port, but metrics are all zeroes, unless `--metric`s CLI arg is specified.

#### Steps to reproduce the behaviour

Add this lines to config.toml
```toml
[Metrics]
Enabled = true
EnabledExpensive = true
HTTP = "0.0.0.0"
Port = 6060
```

Start geth with flags `--pprof --pprof.port=6060 --pprof.addr=0.0.0.0`

Go to `/debug/metrics/prometheus` endpoint and all metrics will be zeroes.

#### Backtrace

````
[backtrace]
````
