### ISSUE TITLE
Post-Merge Private Network

### ISSUE THREAD

**Issue by vidhanmangla** [ethereum/go-ethereum#28813]
The documentation is not very clear regarding how to set up post merge private network. We need to display proof of stake specific genesis file configurations.

**Comment by barnabasbusa** [comment]
Would recommend taking a look at [kurtosis](https://github.com/kurtosis-tech/ethereum-package) if you want to do this.

**Comment by karalabe** [comment]
@barnabasbusa Can you generate the network configs and whatnot with kurtosis and then deploy it yourself on bare metal or own hardware?

**Comment by barnabasbusa** [comment]
Yes, kurtosis takes care of it all. 

It generated the genesis based on the parameters you give it (it uses some sane defaults), then spins up the different client pairs that you define. 
e.g:

```yaml
participants:
  - el_client_type: geth
    el_client_image: ethpandaops/geth:master
    cl_client_type: teku
    cl_client_image: ethpandaops/teku:master
  - el_client_type: nethermind
    el_client_image: ethpandaops/nethermind:master
    cl_client_type: prysm
    cl_client_image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
```

This will spin up a 128 validators (64 each), with 2 client pairs, one geth/teku and one nethermind/prysm. 

You can also test different CL/Validators now. All our tooling has been migrated over to kurtosis too, so you can have tooling like dora, assertoor, to check the health of your private network.
