### ISSUE TITLE
`history.state` seems not respected?

### ISSUE THREAD

**Issue by wtdcode** [ethereum/go-ethereum#29170]
#### System information

Docker geth, version `fff3031b0ba3`

Full configuration

```yaml
services:
  geth:
    image: ethereum/client-go:stable
    restart: always
    volumes:
      - /mnt/pool/geth_pebble:/root/.ethereum
      - ./jwt:/root/jwt
    depends_on:
      - lighthouse
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: --syncmode full --authrpc.jwtsecret /root/jwt --db.engine pebble --state.scheme path --http --ws --ws.addr 0.0.0.0
             --http.addr 0.0.0.0 --ws.port 8546 --http.port 8545 --http.vhosts * --ws.origins * --history.state 9000
             --authrpc.addr 0.0.0.0 --authrpc.vhosts geth

  lighthouse:
    image: sigp/lighthouse
    restart: always
    volumes:
      - /mnt/pool/lighthouse:/root/.lighthouse
      - ./jwt:/root/jwt
    command:
      - "lighthouse"
      - "bn"
      - "--network"
      - "mainnet"
      - "--execution-endpoint"
      - "http://geth:8551"
      - "--execution-jwt"
      - "/root/jwt"
      - "--checkpoint-sync-url"
      - "https://mainnet.checkpoint.sigp.io"
      - "--disable-deposit-contract-sync"
```

#### Expected behaviour

The last 9000 block state is preserved.

#### Actual behaviour

Getting `missing trie node` when going out of 128 blocks.

#### Steps to reproduce the behaviour

`curl` with `eth_getStorageAt`:

```
curl -H 'Content-Type: application/json'  -X POST --data '{"jsonrpc":"2.0", "method": "eth_getStorageAt", "params": ["0xdAC17F958D2ee523a2206206994597C13D831ec7", "0", "0x12780eb"], "id": 1}' http://127.0.0.1:8545
```

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing trie node d18ef28c6b034c4a6142e7f2c1a62ee2e785d1a3bc6ea07a0cfa6adf7a2b173d (path ) state 0xd18ef28c6b034c4a6142e7f2c1a62ee2e785d1a3bc6ea07a0cfa6adf7a2b173d is not available"}}
```

Note `0x12780eb` is roughly 2400 blocks behind at the time of reporting, much less 9000.
