### ISSUE TITLE
Command options as k8s ConfigMap?

### ISSUE THREAD

**Issue by khteh** [ethereum/go-ethereum#31034]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

How to configure all the command options as k8s ConfigMap?
```
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:v1.14.12
          imagePullPolicy: Always
          args:
            - --holesky
            - --http
            - --http.addr=0.0.0.0
            - --http.vhosts=geth
            - --ws
            - --ws.addr=0.0.0.0
            - --authrpc.jwtsecret=/tmp/jwtsecret
            - --datadir=/data
```
I would love these to be organized into ConfigMap instead of in the STS manifest file.
